version: "3.7"

services:

  postgresql:
    image: postgres:13.2
    restart: unless-stopped
    env_file: .env
    ports:
    - 5432:5432
    volumes:
    - postgresql_volume:/var/lib/postgresql/data/
    networks:
    - default

volumes:
  postgresql_volume:
